import Head from "next/head";

import Image from "next/image";
import portrait from "../assets/portrait.webp";

export default function AboutPage() {
  return (
    <>
      <Head>
        <title>Brian Bancroft</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-prose mx-auto py-5">
        <h1 className="text-3xl">Brian Bancroft</h1>

        <p className="my-2">
          I am a software developer who lives in Ladysmith, BC.{" "}
        </p>

        <p className="my-2">
          While I currently work as a front-end developer, I try to work as
          close to fullstack as is possible. I am proficient with building REST
          APIs and using/modelling data with SQL databases and have some
          proficiency with document databases. For front-end work, I stick as
          close as possible with component-based frameworks such as React,
          Svelte and Vue, though I have had worked with MVC-based frameworks in
          the past including Ember.
        </p>

        <p className="my-2">
          I spent a lot of my engergy on frontend testing. I still find it as a
          discipline to be both flimsy and needed as our applications become
          increasingly complex.
        </p>

        <section className="grid grid-cols-1 gap-2 md:grid-cols-2 my-8">
          <div>
            <h2 className="text-xl my-3 ">Experience</h2>
            <ol>
              <li>
                Sparkgeo <span className="text-sm italic">(2018 - *)</span>
              </li>
              <li>
                CareerJSM <span className="text-sm italic">(2017-2018)</span>
              </li>
              <li>
                Sight Surveillance (Integrity Industries North) (2014-2016)
              </li>
            </ol>
            <h2 className="text-xl my-3">Programming Areas of Interest</h2>
            <ol>
              <li>
                JavaScript/TypeScript{" "}
                <span className="text-sm italic">(2014)</span>
              </li>
              <li>
                Ruby on Rails <span className="text-sm italic">(2016)</span>
              </li>
              <li>
                Python <span className="text-sm italic">(2014)</span>
              </li>
              <li>
                Rust <span className="text-gray-600 italic">(2021)</span>
              </li>
            </ol>
          </div>

          <figure>
            <Image
              src={portrait}
              alt="Portrait of Brian"
              width={300}
              height={450}
              layout="intrinsic"
            />
            <figcaption className="italic">
              Casual winter hike at Heart Lake.
            </figcaption>
          </figure>
        </section>
      </main>
    </>
  );
}
