import Head from "next/head";
import Image from "next/image";

export default function AboutPage() {
  return (
    <>
      <Head>
        <title>Brian Bancroft</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>about</main>
    </>
  );
}
