import Head from "next/head";

import { getAllPostsByFrontMatter } from "../lib/getAllPostsByFrontmatter";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Brian Bancroft</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Home Page</main>
    </>
  );
}

export async function getStaticProps(context) {
  const posts = await getAllPostsByFrontMatter("blog");

  console.log("Posts ", posts);

  return { props: {} };
}
