import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import matter from "gray-matter";

import fs from "fs";
import path from "path";

import { getAllPostsByFrontMatter } from "../lib/getAllPostsByFrontmatter";

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Brian Bancroft</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Home Page</main>
    </div>
  );
}

export async function getStaticProps(context) {
  const posts = await getAllPostsByFrontMatter("blog");

  console.log("Posts ", posts);

  return { props: {} };
}
