import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import matter from "gray-matter";

import fs from "fs";
import path from "path";

export default function Home(props) {
  console.log("Props ", props);

  return (
    <div className={styles.container}>
      <Head>
        <title>Brian Bancroft</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Home Page</main>
    </div>
  );
}

export async function getStaticProps(context) {
  console.log("hello world");

  const POSTS_PATH = path.join(process.cwd(), "pages", "posts");

  const postFilePaths = fs
    .readdirSync(POSTS_PATH)
    // Only include md(x) files
    .filter((path) => /\.mdx?$/.test(path));

  const posts = postFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(POSTS_PATH, filePath));
    const { data: meta } = matter(source);

    const url = `/posts/${filePath.split(".")}`;

    return {
      meta,
      url,
    };
  });

  return { props: { posts } };
}
